import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";
import {
  Send,
  Bot,
  ShieldAlert,
  Gauge,
  FileText,
} from "lucide-react";

interface Summary {
  summary?: string;
  risk_level?: string;
  confidence?: number;
  recommendations?: string[];
}

interface CopilotProps {
  summary: Summary;
}

export default function Copilot({ summary }: CopilotProps) {
  const [messages, setMessages] = useState<
    { role: "user" | "ai"; text: string }[]
  >([]);

  const [input, setInput] = useState("");

  const send = (e: React.FormEvent) => {
    e.preventDefault();

    if (!input.trim()) return;

    setMessages((m) => [...m, { role: "user", text: input }]);

    setTimeout(() => {
      setMessages((m) => [
        ...m,
        {
          role: "ai",
          text:
            "Interactive AI chat will be added in the next version. This panel currently displays the investigation summary generated by Gemini.",
        },
      ]);
    }, 500);

    setInput("");
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      className="glass glass-hover flex h-full flex-col overflow-hidden rounded-2xl"
    >
      <div className="flex items-center gap-2.5 border-b border-white/5 px-5 py-3.5">
        <Bot className="h-5 w-5 text-cyan-500" />

        <h2 className="text-sm font-semibold text-white">
          AI Investigation Summary
        </h2>

        <span className="ml-auto rounded-full bg-emerald-500/10 px-2 py-1 text-[10px] text-emerald-400">
          LIVE
        </span>
      </div>

      <div className="flex-1 overflow-y-auto p-5 space-y-4">
        <div className="rounded-xl border border-cyan-500/20 bg-slate-900/40 p-4">
          <div className="flex items-center gap-2 mb-2">
            <ShieldAlert className="h-4 w-4 text-red-400" />
            <span className="text-xs uppercase text-slate-400">
              Risk Level
            </span>
          </div>

          <p className="text-lg font-semibold text-white">
            {summary?.risk_level ?? "Unknown"}
          </p>
        </div>

        <div className="rounded-xl border border-cyan-500/20 bg-slate-900/40 p-4">
          <div className="flex items-center gap-2 mb-2">
            <Gauge className="h-4 w-4 text-cyan-400" />
            <span className="text-xs uppercase text-slate-400">
              Confidence
            </span>
          </div>

          <p className="text-lg font-semibold text-white">
            {summary?.confidence ?? 0}%
          </p>
        </div>

        <div className="rounded-xl border border-cyan-500/20 bg-slate-900/40 p-4">
          <div className="flex items-center gap-2 mb-2">
            <FileText className="h-4 w-4 text-cyan-400" />
            <span className="text-xs uppercase text-slate-400">
              Summary
            </span>
          </div>

          <p className="text-sm text-slate-300 leading-relaxed">
            {summary?.summary ??
              "Run an investigation to generate an AI summary."}
          </p>
        </div>

        {summary?.recommendations &&
          summary.recommendations.length > 0 && (
            <div className="rounded-xl border border-cyan-500/20 bg-slate-900/40 p-4">
              <h3 className="mb-2 text-xs uppercase text-slate-400">
                Recommendations
              </h3>

              <ul className="space-y-2 text-sm text-slate-300">
                {summary.recommendations.map((item, i) => (
                  <li key={i}>• {item}</li>
                ))}
              </ul>
            </div>
          )}

        <AnimatePresence>
          {messages.map((m, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className={`rounded-xl p-3 text-sm ${
                m.role === "user"
                  ? "bg-cyan-500/10 text-white"
                  : "border border-cyan-500/20 bg-slate-900/40 text-slate-300"
              }`}
            >
              {m.text}
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

      <form
        onSubmit={send}
        className="border-t border-white/5 p-3"
      >
        <div className="relative">
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask about this investigation..."
            className="w-full rounded-xl border border-white/10 bg-slate-900/60 p-3 pr-12 text-sm text-white outline-none"
          />

          <button
            type="submit"
            className="absolute right-2 top-2 rounded-lg bg-cyan-500 p-2 text-black"
          >
            <Send size={16} />
          </button>
        </div>
      </form>
    </motion.div>
  );
}